# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
# - script: echo Tests here!!! ???
#   displayName: 'Unit tests'

# - script: |
#     echo ....
#     echo ...
#   displayName: 'Run a multi-line script'

- task: Restore
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    vstsFeed: '27aae03a-27a6-477f-b1bb-0d4760ace431'
- task: Build
  inputs:
    command: 'build'
    projects: '**/*.csproj'
- task: Unit tests
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj'
    testRunTitle: 'Unit tests'
- task: Dockerize
  inputs:
    containerRegistry: 'danieeelfrazuredevops|Azure Container Registry'
    repository: 'danielfr-softplan-rate-services-api'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: |
      $(Build.BuildId)
      latest